[package]
edition = "2021"
exclude = ["index.node"]
license = "GPL-3.0"
name = "desktop_proxy"
version = "0.0.0"
publish = false

[dependencies]
anyhow = "=1.0.94"
desktop_core = { path = "../core" }
futures = "=0.3.31"
log = "=0.4.25"
simplelog = "=0.12.2"
tokio = { version = "=1.43.0", features = ["io-std", "io-util", "macros", "rt"] }
tokio-util = { version = "=0.7.13", features = ["codec"] }

[target.'cfg(target_os = "macos")'.dependencies]
embed_plist = "=1.2.2"
