[package]
edition = "2021"
license = "GPL-3.0"
name = "desktop_core"
version = "0.0.0"
publish = false

[features]
default = []
manual_test = []

[dependencies]
aes = "=0.8.4"
anyhow = "=1.0.86"
arboard = { version = "=3.4.0", default-features = false, features = [
  "wayland-data-control",
] }
base64 = "=0.22.1"
cbc = { version = "=0.1.2", features = ["alloc"] }
rand = "=0.8.5"
retry = "=2.0.0"
scopeguard = "=1.2.0"
sha2 = "=0.10.8"
thiserror = "=1.0.61"
typenum = "=1.17.0"

[target.'cfg(windows)'.dependencies]
widestring = "=1.1.0"
windows = { version = "=0.57.0", features = [
  "Foundation",
  "Security_Credentials_UI",
  "Security_Cryptography",
  "Storage_Streams",
  "Win32_Foundation",
  "Win32_Security_Credentials",
  "Win32_System_WinRT",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_WindowsAndMessaging",
] }

[target.'cfg(windows)'.dev-dependencies]
keytar = "=0.1.6"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "=0.9.4"
security-framework = "=2.11.0"
security-framework-sys = "=2.11.0"

[target.'cfg(target_os = "linux")'.dependencies]
gio = "=0.19.5"
libsecret = "=0.5.0"
