[package]
edition = "2021"
license = "GPL-3.0"
name = "desktop_objc"
version = "0.0.0"
publish = false

[features]
default = []

[dependencies]
anyhow = "=1.0.94"
thiserror = "=1.0.69"
tokio = "1.39.1"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "=0.10.0"

[build-dependencies]
cc = "1.0.104"
glob = "0.3.1"
