---
name: Bump Desktop Cask

on:
  push:
    tags:
      - desktop-v**
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  update-desktop-cask:
    name: Update Bitwarden Desktop Cask
    runs-on: macos-11
    steps:
      - name: Login to Azure
        uses: Azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2 # v1.4.7
        with:
          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@main
        with:
          keyvault: "bitwarden-ci"
          secrets: "brew-bump-workflow-pat"

      - name: Update Homebrew cask
        uses: macauley/action-homebrew-bump-cask@445c42390d790569d938f9068d01af39ca030feb # v1.0.0
        with:
          # Required, custom GitHub access token with the 'public_repo' and 'workflow' scopes
          token: ${{ steps.retrieve-secrets.outputs.brew-bump-workflow-pat }}
          org: bitwarden
          tap: Homebrew/homebrew-cask
          cask: bitwarden
          tag: ${{ github.ref }}
          revision: ${{ github.sha }}
          force: true
          dryrun: true
