name: Build

on:
  push:
    branches-ignore:
      - 'l10n_master'
  workflow_dispatch:
    inputs:


jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Set up cloc
        run: |
          sudo apt update
          sudo apt -y install cloc
      - name: Print lines of code
        run: cloc --include-lang TypeScript,JavaScript,HTML,Sass,CSS --vcs git


  setup:
    runs-on: ubuntu-latest
    outputs:
      repo_url: ${{ steps.gen_vars.outputs.repo_url }}
      adj_build_number: ${{ steps.gen_vars.outputs.adj_build_number }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Get Package Version
        id: gen_vars
        run: |
          repo_url=https://github.com/$GITHUB_REPOSITORY.git
          adj_build_num=${GITHUB_SHA:0:7}

          echo "::set-output name=repo_url::$repo_url" 
          echo "::set-output name=adj_build_number::$adj_build_num" 

  locales-test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Testing locales - extName length
        run: |
         found_error=false

         echo "Locales Test"
         echo "============"
         echo "extName string must be 40 characters or less"
         echo
         for locale in $(ls src/_locales/); do
           string_length=$(jq '.extName.message | length' src/_locales/$locale/messages.json)
           if [[ $string_length -gt 40 ]]; then
             echo "$locale: $string_length"
             found_error=true
           fi
         done
         
         if $found_error; then
           echo
           echo "Please fix 'extName' for the locales listed above."
           exit 1
         else
           echo "Test passed!"
         fi 

  build:
    runs-on: windows-latest
    needs: [ setup, locales-test ]
    env:
      REPO_URL: ${{ needs.setup.outputs.repo_url }}
      BUILD_NUMBER: ${{ needs.setup.outputs.adj_build_number }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Set up Node
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: '14'

      - name: Update NPM
        run: |
          npm install -g npm@7

      - name: Print environment
        run: |
          node --version
          npm --version

      - name: npm setup & test
        run: |
          npm install
          npm run dist
          npm run test

      - name: gulp
        run: gulp ci

      - name: Upload opera artifact
        uses: actions/upload-artifact@ee69f02b3dfdecd58bb31b4d133da38ba6fe3700
        with:
          name: dist-opera-${{ env.BUILD_NUMBER }}.zip
          path: dist/dist-opera-${{ env.BUILD_NUMBER }}.zip

      - name: Upload chrome artifact
        uses: actions/upload-artifact@ee69f02b3dfdecd58bb31b4d133da38ba6fe3700
        with:
          name: dist-chrome-${{ env.BUILD_NUMBER }}.zip
          path: dist/dist-chrome-${{ env.BUILD_NUMBER }}.zip

      - name: Upload firefox artifact
        uses: actions/upload-artifact@ee69f02b3dfdecd58bb31b4d133da38ba6fe3700
        with:
          name: dist-firefox-${{ env.BUILD_NUMBER }}.zip
          path: dist/dist-firefox-${{ env.BUILD_NUMBER }}.zip

      - name: Upload edge artifact
        uses: actions/upload-artifact@ee69f02b3dfdecd58bb31b4d133da38ba6fe3700
        with:
          name: dist-edge-${{ env.BUILD_NUMBER }}.zip
          path: dist/dist-edge-${{ env.BUILD_NUMBER }}.zip

      - name: Upload coverage artifact
        uses: actions/upload-artifact@ee69f02b3dfdecd58bb31b4d133da38ba6fe3700
        with:
          name: coverage-${{ env.BUILD_NUMBER }}.zip
          path: coverage/coverage-${{ env.BUILD_NUMBER }}.zip
