---
name: Chromatic

on:
  push:
    paths-ignore:
      - '.github/workflows/**'

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: "16"

      - name: Checkout repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0

      - name: Cache npm
        id: npm-cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: "~/.npm"
          key: ${{ runner.os }}-npm-chromatic-${{ hashFiles('**/package-lock.json') }}

      - name: Install Node dependencies
        run: npm ci
      
      # Manual build the storybook to resolve a chromatic/storybook bug related to TurboSnap
      - name: Build Storybook
        run: npm run build-storybook:ci

      - name: Publish to Chromatic
        uses: chromaui/action@44caff7e88d584b04f79f04e31e819f9a95d4d8f
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: ./storybook-static
          exitOnceUploaded: true
          onlyChanged: true
          externals: "[\"libs/components/**/*.scss\", \"libs/components/tailwind.config*.js\"]"
