---
name: Version Bump
run-name: Version Bump - v${{ inputs.version_number }}

on:
  workflow_dispatch:
    inputs:
      bump_browser:
        description: "Bump Browser?"
        type: boolean
        default: false
      bump_cli:
        description: "Bump CLI?"
        type: boolean
        default: false
      bump_desktop:
        description: "Bump Desktop?"
        type: boolean
        default: false
      bump_web:
        description: "Bump Web?"
        type: boolean
        default: false
      version_number:
        description: "New version (example: '2024.1.0')"
        required: true
      cut_rc_branch:
        description: "Cut RC branch?"
        default: true
        type: boolean

jobs:
  bump_version:
    name: "Bump Version to v${{ inputs.version_number }}"
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Azure - Prod Subscription
        uses: Azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2 # v1.4.7
        with:
          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@main
        with:
          keyvault: "bitwarden-ci"
          secrets: "github-gpg-private-key,
            github-gpg-private-key-passphrase,
            github-pat-bitwarden-devops-bot-repo-scope"

      - name: Checkout Branch
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          ref: main

      - name: Check if RC branch exists
        if: ${{ inputs.cut_rc_branch == true }}
        run: |
          remote_rc_branch_check=$(git ls-remote --heads origin rc | wc -l)
          if [[ "${remote_rc_branch_check}" -gt 0 ]]; then
            echo "Remote RC branch exists."
            echo "Please delete current RC branch before running again."
            exit 1
          fi

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@82a020f1f7f605c65dd2449b392a52c3fcfef7ef # v6.0.0
        with:
          gpg_private_key: ${{ steps.retrieve-secrets.outputs.github-gpg-private-key }}
          passphrase: ${{ steps.retrieve-secrets.outputs.github-gpg-private-key-passphrase }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create Version Branch
        id: create-branch
        run: |
          CLIENTS=()
          if [[ ${{ inputs.bump_browser }} == true ]]; then
            CLIENTS+=("browser")
          fi
          if [[ ${{ inputs.bump_cli }} == true ]]; then
            CLIENTS+=("cli")
          fi
          if [[ ${{ inputs.bump_desktop }} == true ]]; then
            CLIENTS+=("desktop")
          fi
          if [[ ${{ inputs.bump_web }} == true ]]; then
            CLIENTS+=("web")
          fi
          printf -v joined '%s,' "${CLIENTS[@]}"
          echo "client=${joined%,}" >> $GITHUB_OUTPUT

          NAME=version_bump_${{ github.ref_name }}_${{ inputs.version_number }}
          git switch -c $NAME
          echo "name=$NAME" >> $GITHUB_OUTPUT

      ########################
      # VERSION BUMP SECTION #
      ########################

      ### Browser
      - name: Browser - Verify input version
        if: ${{ inputs.bump_browser == true }}
        env:
          NEW_VERSION: ${{ inputs.version_number }}
        run: |
          CURRENT_VERSION=$(cat package.json | jq -r '.version')

          # Error if version has not changed.
          if [[ "$NEW_VERSION" == "$CURRENT_VERSION" ]]; then
            echo "Version has not changed."
            exit 1
          fi

          # Check if version is newer.
          printf '%s\n' "${CURRENT_VERSION}" "${NEW_VERSION}" | sort -C -V
          if [ $? -eq 0 ]; then
            echo "Version check successful."
          else
            echo "Version check failed."
            exit 1
          fi
        working-directory: apps/browser

      - name: Bump Browser Version
        if: ${{ inputs.bump_browser == true }}
        run: npm version --workspace=@bitwarden/browser ${{ inputs.version_number }}

      - name: Bump Browser Version - Manifest
        if: ${{ inputs.bump_browser == true }}
        uses: bitwarden/gh-actions/version-bump@main
        with:
          version: ${{ inputs.version_number }}
          file_path: "apps/browser/src/manifest.json"

      - name: Bump Browser Version - Manifest v3
        if: ${{ inputs.bump_browser == true }}
        uses: bitwarden/gh-actions/version-bump@main
        with:
          version: ${{ inputs.version_number }}
          file_path: "apps/browser/src/manifest.v3.json"

      - name: Run Prettier after Browser Version Bump
        if: ${{ inputs.bump_browser == true }}
        run: |
          npm install -g prettier
          prettier --write apps/browser/src/manifest.json
          prettier --write apps/browser/src/manifest.v3.json

      ### CLI
      - name: CLI - Verify input version
        if: ${{ inputs.bump_cli == true }}
        env:
          NEW_VERSION: ${{ inputs.version_number }}
        run: |
          CURRENT_VERSION=$(cat package.json | jq -r '.version')

          # Error if version has not changed.
          if [[ "$NEW_VERSION" == "$CURRENT_VERSION" ]]; then
            echo "Version has not changed."
            exit 1
          fi

          # Check if version is newer.
          printf '%s\n' "${CURRENT_VERSION}" "${NEW_VERSION}" | sort -C -V
          if [ $? -eq 0 ]; then
            echo "Version check successful."
          else
            echo "Version check failed."
            exit 1
          fi
        working-directory: apps/cli

      - name: Bump CLI Version
        if: ${{ inputs.bump_cli == true }}
        run: npm version --workspace=@bitwarden/cli ${{ inputs.version_number }}

      ### Desktop
      - name: Desktop - Verify input version
        if: ${{ inputs.bump_desktop == true }}
        env:
          NEW_VERSION: ${{ inputs.version_number }}
        run: |
          CURRENT_VERSION=$(cat package.json | jq -r '.version')

          # Error if version has not changed.
          if [[ "$NEW_VERSION" == "$CURRENT_VERSION" ]]; then
            echo "Version has not changed."
            exit 1
          fi

          # Check if version is newer.
          printf '%s\n' "${CURRENT_VERSION}" "${NEW_VERSION}" | sort -C -V
          if [ $? -eq 0 ]; then
            echo "Version check successful."
          else
            echo "Version check failed."
            exit 1
          fi
        working-directory: apps/desktop

      - name: Bump Desktop Version - Root
        if: ${{ inputs.bump_desktop == true }}
        run: npm version --workspace=@bitwarden/desktop ${{ inputs.version_number }}

      - name: Bump Desktop Version - App
        if: ${{ inputs.bump_desktop == true }}
        run: npm version ${{ inputs.version_number }}
        working-directory: "apps/desktop/src"

      ### Web
      - name: Web - Verify input version
        if: ${{ inputs.bump_web == true }}
        env:
          NEW_VERSION: ${{ inputs.version_number }}
        run: |
          CURRENT_VERSION=$(cat package.json | jq -r '.version')

          # Error if version has not changed.
          if [[ "$NEW_VERSION" == "$CURRENT_VERSION" ]]; then
            echo "Version has not changed."
            exit 1
          fi

          # Check if version is newer.
          printf '%s\n' "${CURRENT_VERSION}" "${NEW_VERSION}" | sort -C -V
          if [ $? -eq 0 ]; then
            echo "Version check successful."
          else
            echo "Version check failed."
            exit 1
          fi
        working-directory: apps/web

      - name: Bump Web Version
        if: ${{ inputs.bump_web == true }}
        run: npm version --workspace=@bitwarden/web-vault ${{ inputs.version_number }}

      ########################

      - name: Setup git
        run: |
          git config --local user.email "106330231+bitwarden-devops-bot@users.noreply.github.com"
          git config --local user.name "bitwarden-devops-bot"

      - name: Check if version changed
        id: version-changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes_to_commit=TRUE" >> $GITHUB_OUTPUT
          else
            echo "changes_to_commit=FALSE" >> $GITHUB_OUTPUT
            echo "No changes to commit!";
          fi

      - name: Commit files
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        env:
          CLIENT: ${{ steps.create-branch.outputs.client }}
          VERSION: ${{ inputs.version_number }}
        run: git commit -m "Bumped ${CLIENT} version to ${VERSION}" -a

      - name: Push changes
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        env:
          PR_BRANCH: ${{ steps.create-branch.outputs.name }}
        run: git push -u origin $PR_BRANCH

      - name: Create Version PR
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        id: create-pr
        env:
          GH_TOKEN: ${{ steps.retrieve-secrets.outputs.github-pat-bitwarden-devops-bot-repo-scope }}
          PR_BRANCH: ${{ steps.create-branch.outputs.name }}
          TITLE: "Bump ${{ steps.create-branch.outputs.client }} version to ${{ inputs.version_number }}"
        run: |
          PR_URL=$(gh pr create --title "$TITLE" \
            --base "main" \
            --head "$PR_BRANCH" \
            --label "version update" \
            --label "automated pr" \
            --body "
              ## Type of change
              - [ ] Bug fix
              - [ ] New feature development
              - [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
              - [ ] Build/deploy pipeline (DevOps)
              - [X] Other

              ## Objective
              Automated ${{ steps.create-branch.outputs.client }} version bump to ${{ inputs.version_number }}")
          echo "pr_number=${PR_URL##*/}" >> $GITHUB_OUTPUT

      - name: Approve PR
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.create-pr.outputs.pr_number }}
        run: gh pr review $PR_NUMBER --approve

      - name: Merge PR
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        env:
          GH_TOKEN: ${{ steps.retrieve-secrets.outputs.github-pat-bitwarden-devops-bot-repo-scope }}
          PR_NUMBER: ${{ steps.create-pr.outputs.pr_number }}
        run: gh pr merge $PR_NUMBER --squash --auto --delete-branch

  cut_rc:
    name: Cut RC branch
    needs: bump_version
    if: ${{ inputs.cut_rc_branch == true }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: main

      ### Browser
      - name: Browser - Verify version has been updated
        if: ${{ inputs.bump_browser == true }}
        env:
          NEW_VERSION: ${{ inputs.version_number }}
        run: |
          CURRENT_VERSION=$(cat package.json | jq -r '.version')

          # Wait for version to change.
          while [[ "$NEW_VERSION" != "$CURRENT_VERSION" ]]
          do
            echo "Waiting for version to be updated..."
            sleep 10
            git pull --force
          done
        working-directory: apps/browser

      ### CLI
      - name: CLI - Verify version has been updated
        if: ${{ inputs.bump_cli == true }}
        env:
          NEW_VERSION: ${{ inputs.version_number }}
        run: |
          CURRENT_VERSION=$(cat package.json | jq -r '.version')

          # Wait for version to change.
          while [[ "$NEW_VERSION" != "$CURRENT_VERSION" ]]
          do
            echo "Waiting for version to be updated..."
            sleep 10
            git pull --force
          done
        working-directory: apps/cli

      ### Desktop
      - name: Desktop - Verify version has been updated
        if: ${{ inputs.bump_desktop == true }}
        env:
          NEW_VERSION: ${{ inputs.version_number }}
        run: |
          CURRENT_VERSION=$(cat package.json | jq -r '.version')

          # Wait for version to change.
          while [[ "$NEW_VERSION" != "$CURRENT_VERSION" ]]
          do
            echo "Waiting for version to be updated..."
            sleep 10
            git pull --force
          done
        working-directory: apps/desktop

      ### Web
      - name: Web - Verify version has been updated
        if: ${{ inputs.bump_web == true }}
        env:
          NEW_VERSION: ${{ inputs.version_number }}
        run: |
          CURRENT_VERSION=$(cat package.json | jq -r '.version')

          # Wait for version to change.
          while [[ "$NEW_VERSION" != "$CURRENT_VERSION" ]]
          do
            echo "Waiting for version to be updated..."
            sleep 10
            git pull --force
          done
        working-directory: apps/web

      - name: Cut RC branch
        run: |
          git switch --quiet --create rc
          git push --quiet --set-upstream origin rc
