---
name: Auto Bump Desktop Version

on:
  push:
    tags:
      - desktop-v**

jobs:
  bump-version:
    name: Bump Desktop Version
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Azure - CI Subscription
        uses: Azure/login@e15b166166a8746d1a47596803bd8c1b595455cf # v1.6.0
        with:
          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

      - name: Retrieve bot secrets
        id: retrieve-bot-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@main
        with:
          keyvault: bitwarden-ci
          secrets: "github-pat-bitwarden-devops-bot-repo-scope"

      - name: Trigger Version Bump workflow
        env:
          GH_TOKEN: ${{ steps.retrieve-bot-secrets.outputs.github-pat-bitwarden-devops-bot-repo-scope }}
        run: |
          echo '{"cut_rc_branch": "false",
                 "bump_browser": "false",
                 "bump_cli": "false",
                 "bump_desktop": "true",
                 "bump_web": "false"}' | \
          gh workflow run version-bump.yml --json --repo bitwarden/clients
